name = "eccentric-equator"
main = "./dist/_worker.js/index.js"
pages_build_output_dir = "./dist"
compatibility_date = "2025-05-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
